server:
  port: 80
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.100:3306/test?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

